version: '3'
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data:rw

  postgres:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "uapoly"
      POSTGRES_PASSWORD: "uapoly"
      POSTGRES_DB: "uapoly"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
  redis-data:
