version: '3'
services:

  app:
    image: node:19-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "uapoly"
      POSTGRES_PASSWORD: "uapoly"
      POSTGRES_DB: "uapoly"
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:

